# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b0687058c75b9fe51fdfcc37ab8ab4e9d4c144c07d7b306ce8a88e294cb491d9636442ee2debdcd4228ff3bb9e134d10cebdbbdfdbefd2c882a1cea73a1c573

test:
  secret_key_base: 17b79b0116ce9e51bd0bdf959b5a867e86aaaf806a586067c6ce81bf7b66d21775a089133cee5bf80d2e03d7abf068281e659c4c46f9cc98a8279dca4c3768e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
